# One of 'error', 'warn', 'info', 'verbose', debug', 'silly'
loglevel: 'silly'
port: 5000
mqtt:
  retained: false
  # URL to MQTT broker
  url: 'mqtt://192.168.1.200'
  # Configuration passed to the MQTT library
  options:
    username: 'mqtt_username'
    password: 'mqtt_password'